# ENSURE RENDER DEPLOYMENT REMAINS FREE.

databases:
  - name: llmeetcode-db
    plan: free
    databaseName: llmeetcode
    user: llmeetcode

services:
  - type: web
    name: llmeetcode
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: llmeetcode-db
          property: connectionString

version: "1"
